version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development 
      # Add your environment variables here
      # - DATABASE_URL=postgresql://user:password@postgres:5432/mydb
      # - NEXTAUTH_SECRET=your-secret-key
      # - NEXTAUTH_URL=http://localhost:3000
    volumes:
      # Optional: Mount for development with hot reload
       - ./:/app/
      # - /app/node_modules
      # - /app/.next
    #depends_on:
    #  - postgres
    #  - redis
    command: "/bin/sh -c 'tail -f /dev/null'"
    restart: unless-stopped

  # Optional: PostgreSQL database
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: myapp
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - app-network
  #   restart: unless-stopped

  # Optional: Redis for caching/sessions
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - app-network
  #   restart: unless-stopped
  #   command: redis-server --appendonly yes

  # Optional: Nginx reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - nextjs-app
  #   networks:
  #     - app-network
  #   restart: unless-stopped